# Generated by Django 3.2.9 on 2022-01-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_description',
            name='id',
        ),
        migrations.AlterField(
            model_name='job_description',
            name='Job_Id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job_description',
            name='Summercamp_Id',
            field=models.CharField(max_length=30),
        ),
    ]
