# Generated by Django 3.2.9 on 2022-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0002_auto_20220127_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_detail',
            name='Summercamp_Id',
            field=models.CharField(max_length=30),
        ),
    ]
